=== RBavithra/DTD/InternalDTD.dtd
<!ELEMENT library (book*)>
<!ELEMENT book (title, author, genre, publication_year)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT publication_year (#PCDATA)>


<!ATTLIST book id CDATA #REQUIRED>

=== RBavithra/DTD/dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE library SYSTEM "InternalDTD.dtd"[

<!ENTITY a "programming Language">
<!ENTITY b "Fantasy">
]>
<library>
    <book id="1">
        <title>Let Us C</title>
        <author>Yashavant Kanetkar</author>
        <genre>&a;</genre>
        <publication_year>2002</publication_year>
    </book>

    <book id="2">
        <title>Java-The Complete reference</title>
        <author>Herbert Schildt</author>
        <genre>&a;</genre>
        <publication_year>2005</publication_year>
    </book>

    <book id="3">
        <title>Python-The Complete reference</title>
        <author>Martin C. Brown</author>
        <genre>&a;</genre>
        <publication_year>2001</publication_year>
    </book>

    <book id="4">
        <title>Harry Potter</title>
        <author>J.K. Rowling</author>
        <genre>&b;</genre>
        <publication_year>1997</publication_year>
    </book>

    <book id="5">
        <title>Earthsea</title>
        <author>Ursula K.Le Guin</author>
        <genre>&b;</genre>
        <publication_year>1968</publication_year>
    </book>
        
</library>
